version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"

  producto-service:
    build: ./producto-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  inventario-service:
    build: ./inventario-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
